/*
	*******************************************************************************
	R3ditor V3 - database.js
	By TheMitoSan

	This file is responsible for database. yep.
	*******************************************************************************
*/
tempFn_DATABASE = {

	/*
		Item Database
	*/
	itemDatabase: {
		'00': {name: 'Empty Slot', 									   description: ''},
		'01': {name: 'Combat Knife',								   description: 'It is a simple combat Knife<br><br>It can be very useful when you are low on ammunition. In the hand of those who know how to use, it does damage!'},
		'02': {name: 'Sigpro SP 2009 handgun',						   description: 'Sigpro SP 2009 Handgun<br><br>This is the Carlos alternative pistol.<br>Not a big deal but it can help you if you\'re in the worst...'},
		'03': {name: 'Beretta M92F handgun',						   description: 'M92F special version of S.T.A.R.S made by Kendo.<br><br>There is a legend has it that those who have no life play using it without ever reloading.'},
		'04': {name: 'Shotgun Benelli M3S',							   description: 'This is a Benelli M3S Shotgun but with a sawed-off barrel.<br><br>It can be a great help if you aim up when you have an enemy nearby!'},
		'05': {name: 'Magnum M629C',								   description: 'Smith & Wesson M629C .44-caliber magnum revolver<br>It\'s a magnum boy! Just shoot the foot and the head explodes!<br>Even though it\'s absurdly powerful, it doesn\'t quite match the magnum of the previous games. (design)'},
		'06': {name: 'Hk-p Grenade launcher (Normal rounds)',		   description: 'Hk-p Grenade launcher with normal rounds<br><br>It is extremely effective against most enemies in the game.'},
		'07': {name: 'Hk-p Grenade launcher (Fire rounds)',			   description: 'Hk-p Grenade launcher with fire rounds<br><br>It is extremely effective against most enemies in the game.'},
		'08': {name: 'Hk-p Grenade launcher (Acid rounds)',			   description: 'Hk-p Grenade launcher with acid rounds<br><br>It is extremely effective against the worm you find in the cemetery (park).'},
		'09': {name: 'Hk-p Grenade launcher (Freeze rounds)',		   description: 'Hk-p Grenade launcher with freeze rounds<br><br>It is extremely effective in battles against nemesis.'},
		'0a': {name: 'M66 Rocket Launcher', 						   description: 'M66 Rocket Launcher<br><br>By far, this is the best gun of all!<br><br>...but Jesus Christ, it take so long to aim!'},
		'0b': {name: 'Gatling Gun', 								   description: 'Gatling Gun<br><br>One of the most powerful weapons available. The only thing that is bad about her is the time it takes her to fire her projectiles.'},
		'0c': {name: 'Mine Thrower', 								   description: 'By far is one of the most different weapons in the game.<br><br>The best use is in the final battle!'},
		'0d': {name: 'STI Eagle 6.0', 								   description: 'This gun shoots faster than standard pistol and also has a chance to hit the enemy with critical damage, exploding his head (zombie).'},
		'0e': {name: 'M4A1 Assault Rifle (Auto Mode)', 				   description: 'M4A1 Assault Rifle in Auto Mode.<br><br>It\'s a good rifle for those learning how to play the game, but know that there are weapons that are better than it.'},
		'0f': {name: 'M4A1 Assault Rifle (Manual Mode)', 			   description: 'M4A1 Assault Rifle in Manual Mode.<br><br>It\'s a good rifle for those learning how to play the game, but know that there are weapons that are better than it.'},
		'10': {name: 'Western Custom M37',							   description: 'Western Custom M37 lever action shotgun<br><br>It has a bigger hitbox and can fire faster than the Benelli M3S but on the other hand can\'t shoot stronger projectiles.<br><br>Use when you have several enemies ahead!'},
		'11': {name: 'Sigpro SP 2009 E', 							   description: 'It\'s the same Sigpro that Carlos uses, but with improved bullets.'},
		'12': {name: 'Beretta M92F E',    							   description: 'It\'s the same M93F that Jill uses, only with more powerful bullets.<br><br>The sound of the shot hurts more than the bullet itself!'},
		'13': {name: 'Shotgun Benelli M3S E',        				   description: 'Shotgun Benelli M3S E<br><br>This is the same shotgun, but with bullets that do much more damage than usual.'},
		'14': {name: 'Mine Thrower E',					 			   description: 'This is an improved version of the Mine thrower, with stronger bullets following the enemy.'},
		'15': {name: 'Handgun bullets (9x19 parabellum)', 			   description: 'Ordinary pistol ammunition. You can load 255 of them per inventory slot!'},
		'16': {name: 'Magnum bullets (.44-caliber)', 				   description: 'Smith & Wesson M629C .44 Magnum Ammo.<br><br>Keep in mind that you won\'t find this type of ammunition that easy, so use it wisely'},
		'17': {name: 'Shotgun shells', 								   description: 'You don\'t find that kind of ammunition that easy, so use them wisely!'},
		'18': {name: 'Grenade rounds', 								   description: '\"Simple\" damage ammo - Ideal for eliminating common enemies.'},
		'19': {name: 'Flame rounds',								   description: 'Moderate damage ammo - Ideal for eliminating different enemies.'},
		'1a': {name: 'Acid rounds',									   description: 'Advance damage ammo - Ideal for fighting the worm in the park\'s cemetery.'},
		'1b': {name: 'Freeze rounds', 								   description: 'Extreme damage ammo - Ideal for fighting nemesis.'},
		'1c': {name: 'Minethrower rounds', 							   description: 'Mine thrower ammunition - Perfect for use in conveniently positioned incinerator locations!'},
		'1d': {name: 'Assault Rifle clip (5.56 NATO rounds)', 		   description: 'M4A1 Rifle Ammo - This is the type of ammo you only find in the protagonist\'s item box!'},
		'1e': {name: 'Enhanced handgun bullets', 					   description: 'Improved Pistol Bullets.<br>Use and abuse the Reloading tool to get them!'},
		'1f': {name: 'Enhanced shotgun shells', 					   description: 'Improved Shotgun shells - Use and abuse the Reloading tool to get them!.'},
		'20': {name: 'First aid spray', 							   description: 'This spray can recover your entire life minus the poison status.'},
		'21': {name: 'Green Herb', 									   description: 'This herb can heal only a little of your life without removing the poisoning status.'},
		'22': {name: 'Blue Herb', 									   description: 'Used to remove poison status.<br><br>On <u>NIGHTMARE MOD</u>, combine two of these to make a green herb!'},
		'23': {name: 'Red Herb',									   description: 'It alone does absolutely nothing - but when combined with the green, it heals your life completely.'},
		'24': {name: '2x Green Herbs', 						    	   description: 'This combination can heal a little more than one herb, but it does not fully restore its life and does not remove poisoning status.'},
		'25': {name: 'Mix of Green and Blue Herbs', 				   description: 'This combination can heal some of your life and remove the poison status.'},
		'26': {name: 'Mix of Green and Red Herbs', 					   description: 'This combination can heal your life completely without removing poisoning status.'},
		'27': {name: 'Mix of 3 Green Herbs', 						   description: 'This combination can heal your life completely without removing poisoning status.'},
		'28': {name: 'Mix of 2x Green Herbs + Blue Herb', 			   description: 'This combination can heal little more than a green weed alone and removes the poison status.'},
		'29': {name: 'Mix of all Herbs',		     				   description: 'This combination completely heals your life, including removing the poison status of the current character.'},
		'2a': {name: 'First aid spray kit',	 						   description: 'This is a kit of Aid Spray that supports up to three first aid kit units.'},
		'2b': {name: 'Square crank', 								   description: 'Square Tip Crank - Used in uptown to open a cabinet full of grenade launcher bullets.'},
		'2c': {name: '(BOTU) Red Coin',								   description: 'BOTU!<br><br>A coin with the symbol of \"Nosferatu\" in red color.<br><br>Item discarded during the development process.'},
		'2d': {name: '(BOTU) Blue Coin', 							   description: 'BOTU!<br><br>A coin with the symbol of \"Nosferatu\" in blue color.<br><br>Item discarded during the development process.'},
		'2e': {name: '(BOTU) Golden Coin',							   description: 'BOTU!<br><br>A coin with the symbol of \"Nosferatu\" in golden color.<br><br>Item discarded during the development process.'},
		'2f': {name: 'Jill\'s S.T.A.R.S card', 						   description: 'Jill Valentine S.T.A.R.S ID Card.<br>Used to get the drawer password in the RPD file room if you run away from nemesis.'},
		'30': {name: '(BOTU) Oil can labelled \'Giga Oil\'',    	   description: 'BOTU!<br><br>This item would be used to make the item \"Mixed Oil\".<br><br>Item discarded during the development process.'},
		'31': {name: 'Battery', 									   description: 'Battery used to power the elevator that leads to the power station in Downtown.'},
		'32': {name: 'Fire hook', 									   description: 'Crowbar used to open a trapdoor in the restaurant.'},
		'33': {name: 'Power cable', 								   description: 'Power cord found in a car in a garage parking lot.<br>Use it on the trolley to make it work.'},
		'34': {name: 'Fuse', 										   description: 'Fuse obtained at the power station. <br> Use it on the trolley to make it work.'},
		'35': {name: '(BOTU) Cut Fire Hose',						   description: 'BOTU!<br>Supposedly this fire hose was supposed to be cut off to make you roam even further around the city!<br><br>Item discarded during the development process.'},
		'36': {name: 'Oil Additive', 								   description: 'Additive to be mixed with oil found at the gas station.'},
		'37': {name: 'Brad Vicker\'s card case', 					   description: 'Brad Vickers Wallet.<br>Inside is a ID Card.'},
		'38': {name: 'Brad Vicker\'s S.T.A.R.S card',				   description: 'Brad Vickers S.T.A.R.S ID Card<br><br>Used to get the drawer password in the RPD file room.<br><br>Also, the combinations are: 0513, 0131, 4011 or 4312.'},
		'39': {name: 'Machine oil', 								   description: 'This item alone has no use. Combine it with Oil Additive to get the item Mixed Oil.'},
		'3a': {name: 'Mixed oil', 									   description: 'Use this item near the fuse and power cord to make the tram move.'},
		'3b': {name: '(BOTU) Chains',  							   	   description: 'BOTU!<br><br>These chains were meant to be where you find bullets in the warehouse.<br><br>Item discarded during the development process.'},
		'3c': {name: 'Wrench', 										   description: 'Wrench used to remove the fire hose in Uptown and open the door to the gas station.'},
		'3d': {name: 'Iron pipe', 									   description: 'Iron pipe used in a fireplace in a cemetery storeroom after burning all the firewood present.<br><br>Serves to reveal a secret passage.'},
		'3e': {name: '(BOTU) Fire hose tip', 						   description: 'BOTU!<br><br>Item that is supposed to be used to match the missing fire hose.<br><br>Item discarded during the development process.'},
		'3f': {name: 'Fire hose', 									   description: 'Fire hose used to put out the fire in a corridor in uptown.'},
		'40': {name: 'Tape recorder', 								   description: 'Audio recorder (aka. Walkman) containing the voice of a doctor describing an elbow fracture.<br><br>Used to open the elevator in the hospital.'},
		'41': {name: 'Lighter oil', 								   description: 'Lighter Fluid<br><br>Use it with the lighter closed to get the lighter open.'},
		'42': {name: 'Lighter (Closed)', 				  			   description: 'A lighter that is out of fluid.<br>Combine with Lighter oil to get the lighter open.'},
		'43': {name: 'Lighter (Open)', 				  				   description: 'A lighter that has fluid. It serves to light fireplaces in cemeteries and burn ropes full of oil.'},
		'44': {name: 'Green gem', 									   description: 'Green gem used to open the gate of raccoon City Hall.<br><br>Congratulations to those who had the brilliant idea<br>Design 10/10!'},
		'45': {name: 'Blue gem', 									   description: 'Blue gem used to open the gate of raccoon City Hall.<br><br>Congratulations to those who had the brilliant idea<br>Design 10/10'},
		'46': {name: 'Amber ball', 									   description: 'A brown sphere made of resin extracted from fossilized trees.<br><br>This item is used in the puzzle of the three clocks in the clock tower.'},
		'47': {name: 'Obsidian ball', 								   description: 'Also known as <font title="In Brazilian Portuguese, of course!">Obsidiena</font>, This is a black glass sphere made by a chemical reaction of volcanic lava when cooled. <br> <br> This item is used in the puzzle of the three clocks in the clock tower.'},
		'48': {name: 'Crystal ball', 								   description: 'A simple crystal sphere, used together with two others in a clock tower puzzle.'},
		'49': {name: '(BOTU) Remote control without Batteries',        description: 'BOTU!<br><br>A Remote Control that is out of batteries.<br>I suppose it would be used at the pharmacy to see what the current password is (Aquacure, Safsprin or Adravil).<br><br>Item discarded during the development process.'},
		'4a': {name: '(BOTU) Remote control with Batteries', 		   description: 'BOTU!<br><br>A remote control that has batteries.<br>I suppose it would be used at the pharmacy to see what the current password is (Aquacure, Safsprin or Adravil).<br><br>Item discarded during the development process.'},
		'4b': {name: '(BOTU) AA Batteries',		 					   description: 'BOTU!<br><br>A pair of batteries that would be used to combine with the Remote Without Batteries. It would be used to turn on the Pharmacy TV.<br><br>Item discarded during the development process.'},
		'4c': {name: 'Gold gear', 									   description: 'A golden gear that is part of a mechanical clock system.<br><br>Combine with Silver Gear to form the Item Chronos Gear.'},
		'4d': {name: 'Silver gear', 								   description: 'A silver gear that is part of a mechanical watch system.<br><br>Combine with Gold Gear to form the Item Chronos Gear.'},
		'4e': {name: 'Chronos gear', 								   description: 'Gear composed of Gold Gear and Silver Gear items. <br> <br> Use on the clock tower clock to activate it.'},
		'4f': {name: 'Bronze book',									   description: 'A Bronze book found in the hands of a statue of the mayor of raccoon city.<br><br>Use it in a puzzle near the restaurant (Downtown) to get the Bronze compass.'},
		'50': {name: 'Bronze compass', 								   description: 'A bronze compass found near a restaurant.<br><br>Use it on the statue of the mayor of raccoon to obtain the item Battery.'},
		'51': {name: 'Vaccine medium', 								   description: 'One of the solutions to create the cure against T-Virus.<br><br>Combine with the base vaccine item to create the item \"Vaccine\".'},
		'52': {name: 'Vaccine base', 								   description: 'One of the solutions to create the cure against T-Virus.<br><br>Combine with the item Vaccine medium to create the item \"Vaccine\".'},
		'53': {name: 'Unknown Sigpro SP 2009 handgun', 				   description: 'Aka: Forgotten Pistol!<br><br>I think the Devs decided to put these pistols here just to fill the space, because they don\'t have any ingame utility.'},
		'54': {name: 'Unknown Sigpro SP 2009 handgun', 				   description: 'Aka: Forgotten Pistol!<br><br>I think the Devs decided to put these pistols here just to fill the space, because they don\'t have any ingame utility.'},
		'55': {name: 'Vaccine', 									   description: 'Vaccine created with Vaccine base and Vaccine medium.<br>Use it to cure Jill.'},
		'56': {name: 'Unknown Sigpro SP 2009 handgun', 				   description: 'Aka: Forgotten Pistol!<br><br>I think the Devs decided to put these pistols here just to fill the space, because they don\'t have any ingame utility.'},
		'57': {name: 'Unknown Sigpro SP 2009 handgun', 				   description: 'Aka: Forgotten Pistol!<br><br>I think the Devs decided to put these pistols here just to fill the space, because they don\'t have any ingame utility.'},
		'58': {name: 'Medium base', 								   description: 'Solution used to create the item Vaccine medium.<br>It is used in the laboratory at raccoon hospital, B3.'},
		'59': {name: 'Eagle Parts A', 								   description: 'First part of the weapon STI Eagle 6.0.<br>Combine with item Eagle parts B to form the same.'},
		'5a': {name: 'Eagle Parts B', 								   description: 'Second part of the weapon STI Eagle 6.0.<br>Combine with item Eagle parts A to form the same.'},
		'5b': {name: 'M37 Parts A', 								   description: 'First part of weapon Western Custom M37. <br> Combine with item M37 parts B to form it.'},
		'5c': {name: 'M37 Parts B', 								   description: 'Second part of weapon Western Custom M37. <br> Combine with item M37 parts B to form it.'},
		'5d': {name: 'Unknown Sigpro SP 2009 handgun', 				   description: 'Aka: Forgotten Pistol!<br><br>I think the Devs decided to put these pistols here just to fill the space, because they don\'t have any ingame utility.'},
		'5e': {name: 'Chronos chain', 								   description: 'A key that apparently has no use until you combine it with the Clock tower (winder) key to form the Chronos key.'},
		'5f': {name: 'Rusted crank', 								   description: 'A rusty handle used to (try) open the gas station door.'},
		'60': {name: 'Card key', 									   description: 'Key card used at the abandoned factory near the end.<br><br>Use it to open some doors and unlock an elevator.'},
		'61': {name: 'Gun powder A', 								   description: 'Gunpowder A<br>This gunpowder alone has the power to generate ordinary pistol bullets.'},
		'62': {name: 'Gun powder B', 								   description: 'Gunpowder B<br>This gunpowder alone has the power to generate ordinary shotgun bullets.'},
		'63': {name: 'Gun powder C', 								   description: 'Gunpowder C<br>This gunpowder alone has the power to generate ordinary grenade launcher bullets.'},
		'64': {name: 'Gun powder AA', 								   description: 'Gunpowder AA.<br>This combination can generate more pistol bullets than usual.'},
		'65': {name: 'Gun powder BB', 								   description: 'Gunpowder BB.<br>This combination can generate more shotgun bullets than usual.'},
		'66': {name: 'Gun powder AC', 								   description: 'Gunpowder AC.<br>This combination can generate up to 20 grenade launcher (fire) bullets.'},
		'67': {name: 'Gun powder BC', 								   description: 'Gunpowder BC.<br>This combination can generate up to 20 grenade launcher (acid) bullets.'},
		'68': {name: 'Gun powder CC', 								   description: 'Gunpowder BC.<br>This combination can generate up to 20 grenade launcher (freeze) bullets.'},
		'69': {name: 'Gun powder AAA', 								   description: 'Gunpowder AAA.<br>This combination can generate many pistol bullets.'},
		'6a': {name: 'Gun powder AAB', 								   description: 'Gunpowder AAB.<br>This combination can generate up to 40 shotgun bullets.'},
		'6b': {name: 'Gun powder BBA', 								   description: 'Gunpowder BBA.<br>This combination can generate up to 120 pistol bullets.'},
		'6c': {name: 'Gun powder BBB', 								   description: 'Gunpowder BBB.<br>This combination can generate many shotgun bullets.'},
		'6d': {name: 'Gun powder CCC', 								   description: 'Gunpowder CCC.<br>This combination can generate magnum bullets!'},
		'6e': {name: 'Infinite bullets', 							   description: 'Unfair!<br><br>The deal is simple - combine this wonder with the weapon you want to have infinite ammo and voilá!'},
		'6f': {name: 'Water sample', 								   description: 'Water sample used on a quality meter near the end.<br><br><div class="align-center">~~~BEEP-BOOP~~~</div>'},
		'70': {name: 'System disk', 								   description: 'Disk used to open a security door in abandoned factory.<br><br>Get ready for nemmy!'},
		'71': {name: 'Dummy key', 									   description: 'Apparently the RE3 Devs have forgotten one of the RE2 keys here...'},
		'72': {name: 'Lockpick', 									   description: 'A classic item - It opens doors, cabinets and drawers with simple locks.'},
		'73': {name: 'Warehouse (backdoor) key', 					   description: 'Used at the beginning of the game to leave the warehouse after a short discussion with Dario.'},
		'74': {name: 'Sickroom key (room 402)',						   description: 'Key used on the 4th floor of raccoon hospital.<br>Use it to open the door to room 402, which contains one of the necessary solutions to create the vaccine.'},
		'75': {name: 'Emblem (S.T.A.R.S) key', 						   description: 'Key used to open the classic S.T.A.R.S room at the RPD police station.'},
		'76': {name: '(BOTU) Keyring with four keys',			 	   description: 'BOTU!<br><br>Bunch of keys with unknown use.<br>I believe it is to open several doors in the hospital, as well as the keys of the 1st Resident / Biohazard.<br><br>Item discarded during the development process.'},
		'77': {name: 'Clock tower (bezel) key', 					   description: 'Key used to descend the clock tower stairs in Clock Tower.<br><br>It is one of the only keys that you cannot use directly from inventory.'},
		'78': {name: 'Clock tower (winder) key', 					   description: 'A key that you can even open a door with - but its real purpose is to be combined with the Chronos Chain to become the Chronos key.'},
		'79': {name: 'Chronos key', 								   description: 'A key made of two other keys (Winder and Chronos chain).<br><br>Serves to open the door near the main clock tower lobby.'},
		'7a': {name: 'Unknown Sigpro SP 2009 handgun', 				   description: 'Aka: Forgotten Pistol!<br><br>I think the Devs decided to put these pistols here just to fill the space, because they don\'t have any ingame utility.'},
		'7b': {name: 'Park (Main Gate) key', 						   description: 'Key to the gates of raccoon park.<br>You find it in a save room near the back of the clock tower.'},
		'7c': {name: 'Park (Graveyard) key', 						   description: 'Cemetery tool room key.<br>You find this key near an explosive gallon in the park.'},
		'7d': {name: 'Park (Rear Gate) key', 						   description: 'With this key you can open a lock that is blocking the way to the abandoned factory.'},
		'7e': {name: 'Facility key (No Barcode)', 					   description: 'One of the keys to the abandoned factory.<br>With it you can access a room with an elevator.'},
		'7f': {name: 'Facility key (With Barcode)', 				   description: 'One of the keys to the abandoned factory.<br>With the barcode, you can get the rocket launcher near the end.<br><br>With her you can access a room with an elevator.'},
		'80': {name: 'Boutique key', 								   description: 'Boutique key, where you can change clothes during gameplay.<br><br>This Function is only available in Playstation and Gamecube version.'},
		'81': {name: 'Ink ribbon', 									   description: 'By far, it is one of the most classic items in the entire Resident Evil / Biohazard franchise.<br><br>When in inventory, you can use it on the typewriter to saving your progress.'},
		'82': {name: 'Reloading tool', 								   description: 'With this item, you can create ammo combining with gunpowder.'},
		'83': {name: 'Game inst. A', 								   description: 'This is a manual of how to play Resident Evil 3 / Biohazard 3.<br><br>With this manual, you learn about explosive objects, The 180° Rotation, Emergency Escape, Emergency Bypass, and more.'},
		'84': {name: 'Game inst. B', 								   description: 'This is a manual of how to play Resident Evil 3 / Biohazard 3.<br><br>With this manual, you learn about the Reloading Tool, Gunpowder and it\'s combinations.'},
		'85': {name: '(BOTU) Recipient with liquid inside',			   description: 'BOT... <i>Wait a sec...</i><br><br>With the internal name of \"Game inst. A\", this item can be used as many times as you like when it is in your inventory - it does not change anything in the game.<br>It only works when you get it as a regular item on map.'}
	},

	/*
		MSG Opcode database
	*/
	msgDatabase: {
		'00': {isFunction: !1, char: ' ', 										  length: 1},
		'01': {isFunction: !1, char: '.', 										  length: 1},
		'02': {isFunction: !1, char: 'º', 										  length: 1},
		'03': {isFunction: !1, char: '(SPECIAL CHAR 1)', 						  length: 1},
		'04': {isFunction: !1, char: '(SPECIAL CHAR 2)', 						  length: 1},
		'05': {isFunction: !1, char: '<code><</code>', 							  length: 1},
		'06': {isFunction: !1, char: '<code>></code>', 							  length: 1},
		'07': {isFunction: !1, char: '(SPECIAL CHAR 3)', 						  length: 1},
		'08': {isFunction: !1, char: '(SPECIAL CHAR 4)', 						  length: 1},
		'09': {isFunction: !1, char: '[', 			 	 						  length: 1},
		'0a': {isFunction: !1, char: ']', 			 	 						  length: 1},
		'0b': {isFunction: !1, char: '(Down Arrow)', 	 						  length: 1},
		'0c': {isFunction: !1, char: '0', 										  length: 1},
		'0d': {isFunction: !1, char: '1', 										  length: 1},
		'0e': {isFunction: !1, char: '2', 										  length: 1},
		'0f': {isFunction: !1, char: '3', 										  length: 1},
		'10': {isFunction: !1, char: '4', 										  length: 1},
		'11': {isFunction: !1, char: '5', 										  length: 1},
		'12': {isFunction: !1, char: '6', 										  length: 1},
		'13': {isFunction: !1, char: '7', 										  length: 1},
		'14': {isFunction: !1, char: '8', 										  length: 1},
		'15': {isFunction: !1, char: '9', 										  length: 1},
		'16': {isFunction: !1, char: ':', 										  length: 1},
		'17': {isFunction: !1, char: '.', 										  length: 1},
		'18': {isFunction: !1, char: ',', 										  length: 1},
		'19': {isFunction: !1, char: '^', 										  length: 1},
		'1a': {isFunction: !1, char: '!', 										  length: 1},
		'1b': {isFunction: !1, char: '?', 										  length: 1},
		'1c': {isFunction: !1, char: '$', 										  length: 1},
		'1d': {isFunction: !1, char: 'A', 										  length: 1},
		'1e': {isFunction: !1, char: 'B', 										  length: 1},
		'1f': {isFunction: !1, char: 'C', 										  length: 1},
		'20': {isFunction: !1, char: 'D', 										  length: 1},
		'21': {isFunction: !1, char: 'E', 										  length: 1},
		'22': {isFunction: !1, char: 'F', 										  length: 1},
		'23': {isFunction: !1, char: 'G', 										  length: 1},
		'24': {isFunction: !1, char: 'H', 										  length: 1},
		'25': {isFunction: !1, char: 'I', 										  length: 1},
		'26': {isFunction: !1, char: 'J', 										  length: 1},
		'27': {isFunction: !1, char: 'K', 										  length: 1},
		'28': {isFunction: !1, char: 'L', 										  length: 1},
		'29': {isFunction: !1, char: 'M', 										  length: 1},
		'2a': {isFunction: !1, char: 'N', 										  length: 1},
		'2b': {isFunction: !1, char: 'O', 										  length: 1},
		'2c': {isFunction: !1, char: 'P', 										  length: 1},
		'2d': {isFunction: !1, char: 'Q', 										  length: 1},
		'2e': {isFunction: !1, char: 'R', 										  length: 1},
		'2f': {isFunction: !1, char: 'S', 										  length: 1},
		'30': {isFunction: !1, char: 'T', 										  length: 1},
		'31': {isFunction: !1, char: 'U', 										  length: 1},
		'32': {isFunction: !1, char: 'V', 										  length: 1},
		'33': {isFunction: !1, char: 'W', 										  length: 1},
		'34': {isFunction: !1, char: 'X', 										  length: 1},
		'35': {isFunction: !1, char: 'Y', 										  length: 1},
		'36': {isFunction: !1, char: 'Z', 										  length: 1},
		'37': {isFunction: !1, char: '+', 										  length: 1},
		'38': {isFunction: !1, char: '/', 										  length: 1},
		'39': {isFunction: !1, char: '-', 										  length: 1},
		'3a': {isFunction: !1, char: '\'', 										  length: 1},
		'3b': {isFunction: !1, char: '-', 										  length: 1},
		'3d': {isFunction: !1, char: 'a', 										  length: 1},
		'3e': {isFunction: !1, char: 'b', 										  length: 1},
		'3f': {isFunction: !1, char: 'c', 										  length: 1},
		'40': {isFunction: !1, char: 'd', 										  length: 1},
		'41': {isFunction: !1, char: 'e', 										  length: 1},
		'42': {isFunction: !1, char: 'f', 										  length: 1},
		'43': {isFunction: !1, char: 'g', 										  length: 1},
		'44': {isFunction: !1, char: 'h', 										  length: 1},
		'45': {isFunction: !1, char: 'i', 										  length: 1},
		'46': {isFunction: !1, char: 'j', 										  length: 1},
		'47': {isFunction: !1, char: 'k', 										  length: 1},
		'48': {isFunction: !1, char: 'l', 										  length: 1},
		'49': {isFunction: !1, char: 'm', 										  length: 1},
		'4a': {isFunction: !1, char: 'n', 										  length: 1},
		'4b': {isFunction: !1, char: 'o', 										  length: 1},
		'4c': {isFunction: !1, char: 'p', 										  length: 1},
		'4d': {isFunction: !1, char: 'q', 										  length: 1},
		'4e': {isFunction: !1, char: 'r', 										  length: 1},
		'4f': {isFunction: !1, char: 's', 										  length: 1},
		'50': {isFunction: !1, char: 't', 										  length: 1},
		'51': {isFunction: !1, char: 'u', 										  length: 1},
		'52': {isFunction: !1, char: 'v', 										  length: 1},
		'53': {isFunction: !1, char: 'w', 										  length: 1},
		'54': {isFunction: !1, char: 'x', 										  length: 1},
		'55': {isFunction: !1, char: 'y', 										  length: 1},
		'56': {isFunction: !1, char: 'z', 										  length: 1},
		'57': {isFunction: !1, char: '(Unknown Char / Function Nº 00 - Hex: 57)', length: 1},
		'58': {isFunction: !1, char: '(Unknown Char / Function Nº 01 - Hex: 58)', length: 1},
		'59': {isFunction: !1, char: '(Unknown Char / Function Nº 02 - Hex: 59)', length: 1},
		// Text format
		'5a': {isFunction: !1, char: 'á', 								   		  length: 1},
		'5b': {isFunction: !1, char: 'à', 								   		  length: 1},
		'5c': {isFunction: !1, char: 'â', 								   		  length: 1},
		'5d': {isFunction: !1, char: 'ã', 								   		  length: 1},
		'5e': {isFunction: !1, char: 'é', 								   		  length: 1},
		'5f': {isFunction: !1, char: 'õ', 								   		  length: 1},
		'60': {isFunction: !1, char: 'ç', 								   		  length: 1},
		'61': {isFunction: !1, char: 'ê', 								   		  length: 1},
		'62': {isFunction: !1, char: 'ó', 								   		  length: 1},
		'63': {isFunction: !1, char: '=', 								   		  length: 1},
		// Unknown / unused chars
		'64': {isFunction: !1, char: '(Unknown Char / Function! Hex: 64)', 		  length: 1},
		'65': {isFunction: !1, char: '(Unknown Char / Function! Hex: 65)', 		  length: 1},
		'66': {isFunction: !1, char: '(Unknown Char / Function! Hex: 66)', 		  length: 1},
		'67': {isFunction: !1, char: '(Unknown Char / Function! Hex: 67)', 		  length: 1},
		'68': {isFunction: !1, char: '(Unknown Char / Function! Hex: 68)', 		  length: 1},
		'69': {isFunction: !1, char: '(Unknown Char / Function! Hex: 69)', 		  length: 1},
		'6a': {isFunction: !1, char: '(Unknown Char / Function! Hex: 6A)', 		  length: 1},
		'6b': {isFunction: !1, char: '(Unknown Char / Function! Hex: 6B)', 		  length: 1},
		'6c': {isFunction: !1, char: '(Unknown Char / Function! Hex: 6C)', 		  length: 1},
		'6d': {isFunction: !1, char: '(Unknown Char / Function! Hex: 6D)', 		  length: 1},
		'6e': {isFunction: !1, char: '(Unknown Char / Function! Hex: 6E)', 		  length: 1},
		'6f': {isFunction: !1, char: '(Unknown Char / Function! Hex: 6F)', 		  length: 1},
		'71': {isFunction: !1, char: '(Unknown Char / Function! Hex: 71)', 		  length: 1},
		'72': {isFunction: !1, char: '(Unknown Char / Function! Hex: 72)', 		  length: 1},
		'73': {isFunction: !1, char: '(Unknown Char / Function! Hex: 73)', 		  length: 1},
		'74': {isFunction: !1, char: '(Unknown Char / Function! Hex: 74)', 		  length: 1},
		'75': {isFunction: !1, char: '(Unknown Char / Function! Hex: 75)', 		  length: 1},
		'76': {isFunction: !1, char: '(Unknown Char / Function! Hex: 76)', 		  length: 1},
		'77': {isFunction: !1, char: '(Unknown Char / Function! Hex: 77)', 		  length: 1},
		'78': {isFunction: !1, char: '(Unknown Char / Function! Hex: 78)', 		  length: 1},
		'79': {isFunction: !1, char: '(Unknown Char / Function! Hex: 79)', 		  length: 1},
		'7a': {isFunction: !1, char: '(Unknown Char / Function! Hex: 7A)', 		  length: 1},
		'7b': {isFunction: !1, char: '(Unknown Char / Function! Hex: 7B)', 		  length: 1},
		'7c': {isFunction: !1, char: '(Unknown Char / Function! Hex: 7C)', 		  length: 1},
		'7d': {isFunction: !1, char: '(Unknown Char / Function! Hex: 7D)', 		  length: 1},
		'7e': {isFunction: !1, char: '(Unknown Char / Function! Hex: 7E)', 		  length: 1},
		'7f': {isFunction: !1, char: '(Unknown Char / Function! Hex: 7F)', 		  length: 1},
		'80': {isFunction: !1, char: '(Unknown Char / Function! Hex: 80)', 		  length: 1},
		'81': {isFunction: !1, char: '(Unknown Char / Function! Hex: 81)', 		  length: 1},
		'82': {isFunction: !1, char: '(Unknown Char / Function! Hex: 82)', 		  length: 1},
		'83': {isFunction: !1, char: '(Unknown Char / Function! Hex: 83)', 		  length: 1},
		'84': {isFunction: !1, char: '(Unknown Char / Function! Hex: 84)', 		  length: 1},
		'85': {isFunction: !1, char: '(Unknown Char / Function! Hex: 85)', 		  length: 1},
		'86': {isFunction: !1, char: '(Unknown Char / Function! Hex: 86)', 		  length: 1},
		'87': {isFunction: !1, char: '(Unknown Char / Function! Hex: 87)', 		  length: 1},
		'88': {isFunction: !1, char: '(Unknown Char / Function! Hex: 88)', 		  length: 1},
		'89': {isFunction: !1, char: '(Unknown Char / Function! Hex: 89)', 		  length: 1},
		'8a': {isFunction: !1, char: '(Unknown Char / Function! Hex: 8A)', 		  length: 1},
		'8b': {isFunction: !1, char: '(Unknown Char / Function! Hex: 8B)', 		  length: 1},
		'8c': {isFunction: !1, char: '(Unknown Char / Function! Hex: 8C)', 		  length: 1},
		'8d': {isFunction: !1, char: '(Unknown Char / Function! Hex: 8D)', 		  length: 1},
		'8e': {isFunction: !1, char: '(Unknown Char / Function! Hex: 8E)', 		  length: 1},
		'8f': {isFunction: !1, char: '(Unknown Char / Function! Hex: 8F)', 		  length: 1},
		'90': {isFunction: !1, char: '(Unknown Char / Function! Hex: 90)', 		  length: 1},
		'91': {isFunction: !1, char: '(Unknown Char / Function! Hex: 91)', 		  length: 1},
		'92': {isFunction: !1, char: '(Unknown Char / Function! Hex: 92)', 		  length: 1},
		'93': {isFunction: !1, char: '(Unknown Char / Function! Hex: 93)', 		  length: 1},
		'94': {isFunction: !1, char: '(Unknown Char / Function! Hex: 94)', 		  length: 1},
		'95': {isFunction: !1, char: '(Unknown Char / Function! Hex: 95)', 		  length: 1},
		'96': {isFunction: !1, char: '(Unknown Char / Function! Hex: 96)', 		  length: 1},
		'97': {isFunction: !1, char: '(Unknown Char / Function! Hex: 97)', 		  length: 1},
		'98': {isFunction: !1, char: '(Unknown Char / Function! Hex: 98)', 		  length: 1},
		'99': {isFunction: !1, char: '(Unknown Char / Function! Hex: 99)', 		  length: 1},
		'9a': {isFunction: !1, char: '(Unknown Char / Function! Hex: 9A)', 		  length: 1},
		'9b': {isFunction: !1, char: '(Unknown Char / Function! Hex: 9B)', 		  length: 1},
		'9c': {isFunction: !1, char: '(Unknown Char / Function! Hex: 9C)', 		  length: 1},
		'9d': {isFunction: !1, char: '(Unknown Char / Function! Hex: 9D)', 		  length: 1},
		'9e': {isFunction: !1, char: '(Unknown Char / Function! Hex: 9E)', 		  length: 1},
		'9f': {isFunction: !1, char: '(Unknown Char / Function! Hex: 9F)', 		  length: 1},
		'a1': {isFunction: !1, char: '(Unknown Char / Function! Hex: A1)', 		  length: 1},
		'a2': {isFunction: !1, char: '(Unknown Char / Function! Hex: A2)', 		  length: 1},
		'a3': {isFunction: !1, char: '(Unknown Char / Function! Hex: A3)', 		  length: 1},
		'a4': {isFunction: !1, char: '(Unknown Char / Function! Hex: A4)', 		  length: 1},
		'a5': {isFunction: !1, char: '(Unknown Char / Function! Hex: A5)', 		  length: 1},
		'a6': {isFunction: !1, char: '(Unknown Char / Function! Hex: A6)', 		  length: 1},
		'a7': {isFunction: !1, char: '(Unknown Char / Function! Hex: A7)', 		  length: 1},
		'a8': {isFunction: !1, char: '(Unknown Char / Function! Hex: A8)', 		  length: 1},
		'a9': {isFunction: !1, char: '(Unknown Char / Function! Hex: A9)', 		  length: 1},
		'aa': {isFunction: !1, char: '(Unknown Char / Function! Hex: AA)', 		  length: 1},
		'ab': {isFunction: !1, char: '(Unknown Char / Function! Hex: AB)', 		  length: 1},
		'ac': {isFunction: !1, char: '(Unknown Char / Function! Hex: AC)', 		  length: 1},
		'ad': {isFunction: !1, char: '(Unknown Char / Function! Hex: AD)', 		  length: 1},
		'ae': {isFunction: !1, char: '(Unknown Char / Function! Hex: AE)', 		  length: 1},
		'af': {isFunction: !1, char: '(Unknown Char / Function! Hex: AF)', 		  length: 1},
		'b0': {isFunction: !1, char: '(Unknown Char / Function! Hex: B0)', 		  length: 1},
		'b1': {isFunction: !1, char: '(Unknown Char / Function! Hex: B1)', 		  length: 1},
		'b2': {isFunction: !1, char: '(Unknown Char / Function! Hex: B2)', 		  length: 1},
		'b3': {isFunction: !1, char: '(Unknown Char / Function! Hex: B3)', 		  length: 1},
		'b4': {isFunction: !1, char: '(Unknown Char / Function! Hex: B4)', 		  length: 1},
		'b5': {isFunction: !1, char: '(Unknown Char / Function! Hex: B5)', 		  length: 1},
		'b6': {isFunction: !1, char: '(Unknown Char / Function! Hex: B6)', 		  length: 1},
		'b7': {isFunction: !1, char: '(Unknown Char / Function! Hex: B7)', 		  length: 1},
		'b9': {isFunction: !1, char: '(Unknown Char / Function! Hex: B9)', 		  length: 1},
		'ba': {isFunction: !1, char: '(Unknown Char / Function! Hex: BA)', 		  length: 1},
		'bb': {isFunction: !1, char: '(Unknown Char / Function! Hex: BB)', 		  length: 1},
		'bc': {isFunction: !1, char: '(Unknown Char / Function! Hex: BC)', 		  length: 1},
		'bd': {isFunction: !1, char: '(Unknown Char / Function! Hex: BD)', 		  length: 1},
		'bf': {isFunction: !1, char: '(Unknown Char / Function! Hex: BF)', 		  length: 1},
		'c2': {isFunction: !1, char: '(Unknown Char / Function! Hex: C2)', 		  length: 1},
		'c3': {isFunction: !1, char: '(Unknown Char / Function! Hex: C3)', 		  length: 1},
		'c4': {isFunction: !1, char: '(Unknown Char / Function! Hex: C4)', 		  length: 1},
		'c5': {isFunction: !1, char: '(Unknown Char / Function! Hex: C5)', 		  length: 1},
		'c6': {isFunction: !1, char: '(Unknown Char / Function! Hex: C6)', 		  length: 1},
		'c7': {isFunction: !1, char: '(Unknown Char / Function! Hex: C7)', 		  length: 1},
		'c8': {isFunction: !1, char: '(Unknown Char / Function! Hex: C8)', 		  length: 1},
		'c9': {isFunction: !1, char: '(Unknown Char / Function! Hex: C9)', 		  length: 1},
		'cb': {isFunction: !1, char: '(Unknown Char / Function! Hex: CB)', 		  length: 1},
		'cc': {isFunction: !1, char: '(Unknown Char / Function! Hex: CC)', 		  length: 1},
		'cd': {isFunction: !1, char: '(Unknown Char / Function! Hex: CD)', 		  length: 1},
		'ce': {isFunction: !1, char: '(Unknown Char / Function! Hex: CE)', 		  length: 1},
		'cf': {isFunction: !1, char: '(Unknown Char / Function! Hex: CF)', 		  length: 1},
		'd0': {isFunction: !1, char: '(Unknown Char / Function! Hex: D0)', 		  length: 1},
		'd2': {isFunction: !1, char: '(Unknown Char / Function! Hex: D2)', 		  length: 1},
		'd3': {isFunction: !1, char: '(Unknown Char / Function! Hex: D3)', 		  length: 1},
		'd4': {isFunction: !1, char: '(Unknown Char / Function! Hex: D4)', 		  length: 1},
		'd5': {isFunction: !1, char: '(Unknown Char / Function! Hex: D5)', 		  length: 1},
		'd6': {isFunction: !1, char: '(Unknown Char / Function! Hex: D6)', 		  length: 1},
		'd8': {isFunction: !1, char: '(Unknown Char / Function! Hex: D8)', 		  length: 1},
		'd9': {isFunction: !1, char: '(Unknown Char / Function! Hex: D9)', 		  length: 1},
		'da': {isFunction: !1, char: '(Unknown Char / Function! Hex: DA)', 		  length: 1},
		'db': {isFunction: !1, char: '(Unknown Char / Function! Hex: DB)', 		  length: 1},
		'dc': {isFunction: !1, char: '(Unknown Char / Function! Hex: DC)', 		  length: 1},
		'dd': {isFunction: !1, char: '(Unknown Char / Function! Hex: DD)', 		  length: 1},
		'de': {isFunction: !1, char: '(Unknown Char / Function! Hex: DE)', 		  length: 1},
		'df': {isFunction: !1, char: '(Unknown Char / Function! Hex: DF)', 		  length: 1},
		'e0': {isFunction: !1, char: '(Unknown Char / Function! Hex: E0)', 		  length: 1},
		'e1': {isFunction: !1, char: '(Unknown Char / Function! Hex: E1)', 		  length: 1},
		'e2': {isFunction: !1, char: '(Unknown Char / Function! Hex: E2)', 		  length: 1},
		'e3': {isFunction: !1, char: '(Unknown Char / Function! Hex: E3)', 		  length: 1},
		'e4': {isFunction: !1, char: '(Unknown Char / Function! Hex: E4)', 		  length: 1},
		'e5': {isFunction: !1, char: '(Unknown Char / Function! Hex: E5)', 		  length: 1},
		'e6': {isFunction: !1, char: '(Unknown Char / Function! Hex: E6)', 		  length: 1},
		'e7': {isFunction: !1, char: '(Unknown Char / Function! Hex: E7)', 		  length: 1},
		'e8': {isFunction: !1, char: '(Unknown Char / Function! Hex: E8)', 		  length: 1},
		'e9': {isFunction: !1, char: '(Unknown Char / Function! Hex: E9)', 		  length: 1},
		'eb': {isFunction: !1, char: '(Unknown Char / Function! Hex: EB)', 		  length: 1},
		'ec': {isFunction: !1, char: '(Unknown Char / Function! Hex: EC)', 		  length: 1},
		'ed': {isFunction: !1, char: '(Unknown Char / Function! Hex: ED)', 		  length: 1},
		'ee': {isFunction: !1, char: '(Unknown Char / Function! Hex: EE)', 		  length: 1},
		'ef': {isFunction: !1, char: '(Unknown Char / Function! Hex: EF)', 		  length: 1},
		'f1': {isFunction: !1, char: '(Unknown Char / Function! Hex: F1)', 		  length: 1},
		'f2': {isFunction: !1, char: '(Unknown Char / Function! Hex: F2)', 		  length: 1},
		'f6': {isFunction: !1, char: '(Unknown Char / Function! Hex: F6)', 		  length: 1},

		//
		'f7': {isFunction: !1, char: '(Item Separator)', 				   		  length: 1},
		'ff': {isFunction: !1, char: '(Unknown CHAR)',					   		  length: 1},

		// Special commands (functions)
		'70': {isFunction: !0, char: '(Function: Select Option - Args: ',		  length: 2, prefix: 'SLO'},
		'fa': {isFunction: !0, char: '(Function: Start Message - Text Speed: ',   length: 2, prefix: 'STR'},
		'fe': {isFunction: !0, char: '(Function: End Message - Args: ',			  length: 2, prefix: 'END'},
		'ea': {isFunction: !0, char: '(Function: Show Special Char - Char ID: ',  length: 2, prefix: 'CH1'},
		'f0': {isFunction: !0, char: '(Function: Show Special Char - Char ID: ',  length: 2, prefix: 'CH2'},
		'f8': {isFunction: !0, char: '(Function: Show Item Name - Item ID: ', 	  length: 2, prefix: 'SIN'},
		'f3': {isFunction: !0, char: '(Function: Play SE - SE ID: ',  			  length: 2, prefix: 'PSE'},

		'fb': {isFunction: !0, char: '(Yes / No)',						   		  length: 1, prefix: 'YNO'},
		'a0': {isFunction: !0, char: '(Climax)', 						   		  length: 1, prefix: 'CLX'},
		'fd': {isFunction: !0, char: '(Pause)', 						   		  length: 1, prefix: 'PAU'},
		'fc': {isFunction: !0, char: '<br>',							   		  length: 1, prefix: 'BRL'},

		'f4': {isFunction: !0, char: '(Function: Change Camera - Cam ID: ',		  length: 2, prefix: 'CAM'},
		'f5': {isFunction: !0, char: '(Function: (UNK) Function F5 - Args: ',	  length: 2, prefix: 'UF5'}, // Used on "Septemer, 28" text
		'f9': {isFunction: !0, char: '(Function: Text Color - Color: ',			  length: 2, prefix: 'CTC'},

		/*
			CT-STARS PATCH COMPAT
		*/
		'd7': {isFunction: !1, char: ' ', 										  length: 1},
		'3c': {isFunction: !1, char: 'ã', 										  length: 1},
		'b8': {isFunction: !1, char: 'á', 										  length: 1},
		'be': {isFunction: !1, char: 'ç', 										  length: 1},
		'c0': {isFunction: !1, char: 'é', 										  length: 1},
		'c1': {isFunction: !1, char: 'ê', 										  length: 1},
		'ca': {isFunction: !1, char: 'ó', 										  length: 1},
		'd1': {isFunction: !1, char: 'ú', 										  length: 1}
	},

	/*
		MSG Compiler Char Database
	*/
	msgCompilerCharDatabase: {
		' ':  '00',
		'.':  '01',
		'º':  '02',
		'<':  '05',
		'>':  '06',
		'0':  '0c',
		'"':  '09',
		'"':  '0a',
		'1':  '0d',
		'2':  '0e',
		'3':  '0f',
		'4':  '10',
		'5':  '11',
		'6':  '12',
		'7':  '13',
		'8':  '14',
		'9':  '15',
		':':  '16',
		',':  '18',
		'^':  '19',
		'!':  '1a',
		'?':  '1b',
		'$':  '1c', // I will need to fix this later
		'A':  '1d',
		'B':  '1e',
		'C':  '1f',
		'D':  '20',
		'E':  '21',
		'F':  '22',
		'G':  '23',
		'H':  '24',
		'I':  '25',
		'J':  '26',
		'K':  '27',
		'L':  '28',
		'M':  '29',
		'N':  '2a',
		'O':  '2b',
		'P':  '2c',
		'Q':  '2d',
		'R':  '2e',
		'S':  '2f',
		'T':  '30',
		'U':  '31',
		'V':  '32',
		'W':  '33',
		'X':  '34',
		'Y':  '35',
		'Z':  '36',
		'+':  '37',
		'/':  '38',
		'-':  '39',
		'\'': '3a',
		'-':  '3b',
		'a':  '3d',
		'b':  '3e',
		'c':  '3f',
		'd':  '40',
		'e':  '41',
		'f':  '42',
		'g':  '43',
		'h':  '44',
		'i':  '45',
		'j':  '46',
		'k':  '47',
		'l':  '48',
		'm':  '49',
		'n':  '4a',
		'o':  '4b',
		'p':  '4c',
		'q':  '4d',
		'r':  '4e',
		's':  '4f',
		't':  '50',
		'u':  '51',
		'v':  '52',
		'w':  '53',
		'x':  '54',
		'y':  '55',
		'z':  '56',
		// Format
		'ü':  '51',
		'ú':  '51',
		'ù':  '51',
		'û':  '51',
		'è':  '41',
		'ë':  '41',
		'ò':  '4b',
		'ô':  '4b',
		'ö':  '4b',
		'ã':  '3d',
		'ä':  '3d',
		'í':  '45',
		'ï':  '45',
		'ì':  '45'
	},

	/*
		MSG Compiler Functions Database
	*/
	msgCompilerFunctionDatabase: {
		'SLO': {opcode: '70', length: 2}, // Select Options
		'STR': {opcode: 'fa', length: 2}, // Start message
		'END': {opcode: 'fe', length: 2}, // End message
		'CH1': {opcode: 'ea', length: 2}, // Show Special Char 1
		'CH2': {opcode: 'f0', length: 2}, // Show Special Char 2
		'SIN': {opcode: 'f8', length: 2}, // Show Item Name
		'PSE': {opcode: 'f3', length: 2}, // Play SE
		'CAM': {opcode: 'f4', length: 2}, // Show Camera
		'UF5': {opcode: 'f5', length: 2}, // Unknown function F5
		'CTC': {opcode: 'f9', length: 2}, // Change text color
		//
		'YNO': {opcode: 'fb', length: 1}, // Yes / No Options
		'CLX': {opcode: 'a0', length: 1}, // Climax
		'PAU': {opcode: 'fd', length: 1}, // Pause
		'BRL': {opcode: 'fc', length: 1}  // Break Line
	},

	/*
		SCD Opcode database
	*/
	scdDatabase: {
		'00': [1,  'Null Function [NOP]'],
		'01': [2,  'End Script [EVT_END]'],
		'02': [1,  'Next Event [EVT_NEXT]'],
		'03': [2,  'Event Chain [EVT_CHAIN]'],
		'04': [2,  'Execute Event [EVT_EXEC]'],
		'05': [2,  'Event Kill [EVT_KILL]'],
		'06': [4,  'If [IF]'],
		'07': [4,  'Else [ELSE]'],
		'08': [2,  'End If [END_IF]'],
		'09': [4,  'Sleep [SLEEP]'],
		'0a': [3,  'Sleeping [SLEEPING]'],
		'0b': [1,  'WSLEEP [WSLEEP]'],
		'0c': [1,  'WSLEEPING [WSLEEPING]'],
		'0d': [6,  'For [FOR]'],
		'0e': [5,  'UNK_OPCODE_0 [UNK_OPCODE_0]'],
		'0f': [2,  'End For [END_FOR]'],
		'10': [4,  'While [WHILE]'],
		'11': [2,  'End While [END_WHILE]'],
		'12': [4,  'Do Function [DO_START]'],
		'13': [2,  'End Do [END_DO]'],
		'14': [4,  'SWITCH'],
		'15': [6,  'CASE'],
		'16': [2,  'SWITCH'],
		'17': [2,  'END_SWITCH'],
		'18': [6,  'Go To [GOTO]'],
		'19': [2,  'Run Script [GO_SUB]'],
		'1a': [4,  'RETURN'],
		'1b': [2,  'BREAK'],
		'1c': [1,  'BREAK_POINT'],
		'1d': [4,  'EVAL_CC'],
		'1e': [4,  'Set Timer / Value [SET_TIMER]'],
		'1f': [4,  'SET_DO',],
		'20': [6,  'Execute Calculation [CALC_OP]'],
		'21': [4,  'UNK_OPCODE_1'],
		'22': [2,  'EVT_CUT'],
		'23': [1,  'UNK_OPCODE_2'],
		'24': [2,  'CHASER_EVT_CLR'],
		'25': [4,  'Open Map [MAP_OPEN]'],
		'26': [6,  'POINT_ADD'],
		'27': [1,  'DOOR_CK'],
		'28': [1,  'Game Over [DIEDEMO_ON]'],
		'29': [8,  'DIR_CK'],
		'2a': [6,  'PARTS_SET'],
		'2b': [2,  'VLOOP_SET'],
		'2c': [4,  'OTA_BE_SET'],
		'2d': [4,  'LINE_START'],
		'2e': [6,  'LINE_MAIN'],
		'2f': [2,  'LINE_END'],
		'30': [6,  'Set LIT Position [LIGHT_POS_SET]'],
		'31': [6,  'LIGHT_KIDO_SET'],
		'32': [6,  'Set LIT Color [LIGHT_COLOR_SET]'],
		'33': [4,  'AHEAD_ROOM_SET'],
		'34': [10, 'ESPR_CTR'],
		'35': [6,  'BGM_TBL_CK'],
		'36': [3,  'ITEM_GET_CK'],
		'37': [2,  'OM_REV'],
		'38': [2,  'CHASER_LIFE_INIT'],
		'39': [16, 'PARTS_BOMB'],
		'3a': [16, 'PARTS_DOWN'],
		'3b': [3,  'CHASER_ITEM_SET'],
		'3c': [1,  'WEAPON_CHG_OLD'],
		'3d': [2,  'SEL_EVT_ON'],
		'3e': [2,  'Remove Item [ITEM_LOST]'],
		'3f': [3,  'FLR_SET'],
		'40': [4,  'Set Variable [MEMB_SET]'],
		'41': [4,  'Set Variable 2 [MEMB_SET2]'],
		'42': [4,  'MEMB_CPY'],
		'43': [6,  'MEMB_CMP'],
		'44': [6,  'MEMB_CALC'],
		'45': [4,  'MEMB_CALC2'],
		'46': [11, 'Set Fade [FADE_SET]'],
		'47': [3,  'Char Trigger [WORK_SET]'],
		'48': [4,  'SPD_SET'],
		'49': [1,  'ADD_SPD'],
		'4a': [1,  'ADD_ASPD'],
		'4b': [1,  'ADD_VSPD'],
		'4c': [4,  'Check Boolean [CK]'],
		'4d': [4,  'Set Event Value [SET]'],
		'4e': [6,  'Compare Values [CMP]'],
		'4f': [1,  'RND'],
		'50': [2,  'Change Camera [CUT_CHG]'],
		'51': [1,  'CUT_OLD'],
		'52': [2,  'Lock Camera [CUT_AUTO]'],
		'53': [3,  'Swap Camera [CUT_REPLACE]'],
		'54': [4,  'CUT_BE_SET'],
		'55': [8,  'Set Target Position [POS_SET]'],
		'56': [8,  'DIR_SET'],
		'57': [6,  'SET_VIB0'],
		'58': [6,  'SET_VIB1'],
		'59': [8,  'SET_VIB_FADE'],
		'5a': [2,  'RBJ Trigger [RBJ_SET]'],
		'5b': [6,  'Display Message [MESSAGE_ON]'],
		'5c': [2,  'RAIN_SET'],
		'5d': [1,  'MESSAGE_OFF'],
		'5e': [3,  'SHAKE_ON'],
		'5f': [2,  'Change Weapon [WEAPON_CHG]'],
		'60': [22, 'UNK_OPCODE_3'],
		'61': [32, 'Set Door [DOOR_AOT_SET]'],
		'62': [40, 'Set Door 4P [DOOR_AOT_SET_4P]'],
		'63': [20, 'Set Interactive Object [AOT_SET]'],
		'64': [28, 'Set Interactive Object 4P [AOT_SET_4P]'],
		'65': [10, 'AOT_RESET'],
		'66': [2,  'Run Interactive Object [AOT_ON]'],
		'67': [22, 'Set Item [ITEM_AOT_SET]'],
		'68': [30, 'Set Item 4P [ITEM_AOT_SET_4P]'],
		'69': [14, 'Shadow Effect [KAGE_SET]'],
		'6a': [16, 'SUPER_SET'],
		'6b': [2,  'Check Item [KEEP_ITEM_CK]'],
		'6c': [4,  'KEY_CK'],
		'6d': [4,  'TRG_CK'],
		'6e': [4,  'SCA_ID_SET'],
		'6f': [2,  'OM_BOMB'],
		'70': [16, 'ESPR_ON'],
		'71': [18, 'ESPR_ON2'],
		'72': [22, 'ESPR3D_ON'],
		'73': [24, 'ESPR3D_ON2'],
		'74': [5,  'ESPR_KILL'],
		'75': [2,  'ESPR_KILL2'],
		'76': [3,  'ESPR_KILL_ALL'],
		'77': [12, 'Play SE [SE_ON]'],
		'78': [6,  'BGM_CTL'],
		'79': [4,  'XA_ON'],
		'7a': [2,  'Call Cinematic [MOVIE_ON]'],
		'7b': [6,  'BGM_TBL_SET'],
		'7c': [1,  'Open Inventory [STATUS_ON]'],
		'7d': [24, 'Set Enemy / NPC [EM_SET]'],
		'7e': [2,  'MIZU_DIV'],
		'7f': [40, 'Set 3D Object [OM_SET]'],
		'80': [4,  'Motion Trigger [PLC_MOTION]'],
		'81': [8,  'Set Animation DEST [PLC_DEST]'],
		'82': [10, 'Set Head Animation [PLC_NECK]'],
		'83': [1,  'Player Return [PLC_RET]'],
		'84': [4,  'PLC_FLG'],
		'85': [2,  'PLC_GUN'],
		'86': [1,  'PLC_GUN_EFF'],
		'87': [1,  'PLC_STOP'],
		'88': [4,  'PLC_ROT'],
		'89': [2,  'PLC_CNT'],
		'8a': [1,  'SLPC_RET'],
		'8b': [1,  'SLPC_SCE'],
		'8c': [1,  'PLC_SCE'],
		'8d': [1,  'SPL_WEAPON_CHG'],
		'8e': [4,  'PLC_MOT_NUM'],
		'8f': [2,  'Reset Enemy Animation [EM_RESET]']
	},

	// Game Prefix
	easyGamePrefix: ['DATA_AJ', 'DATA_AU'],
	hardGamePrefix: ['DATA_E', 'DATA_U'],

	/*
		RDT Metadata
	*/

	rdtMetadata: {
		'0000': {name: 'Unknown Map', 					 location: 'Unknown'},
		'R100': {name: 'Warehouse Save Room',			 location: 'Uptown'},
		'R101': {name: 'Warehouse',						 location: 'Uptown'},
		'R102': {name: 'Alley 1', 						 location: 'Uptown'},
		'R103': {name: 'Street 1', 						 location: 'Uptown'},
		'R104': {name: 'Alley 2', 						 location: 'Uptown'},
		'R105': {name: 'Alley 3', 						 location: 'Uptown'},
		'R106': {name: 'Boutique Street', 				 location: 'Uptown'},
		'R107': {name: 'Bar Jack',		 				 location: 'Uptown'},
		'R108': {name: 'Alley 5', 						 location: 'Uptown'},
		'R109': {name: 'Passage to Pharmacy (Day)',		 location: 'Uptown'},
		'R10A': {name: 'Main Street', 					 location: 'Uptown'},
		'R10B': {name: 'Pharmacy Street',  				 location: 'Uptown'},
		'R10C': {name: 'Alley (Save)', 	 				 location: 'Uptown'},
		'R10D': {name: 'Jill\'s Apartment',				 location: 'Uptown'},
		'R10E': {name: 'Alley 6',						 location: 'Uptown'},
		'R10F': {name: 'Boutique', 						 location: 'Uptown'},
		'R110': {name: 'R.P.D. Gate', 				     location: 'Police Station'},
		'R111': {name: 'R.P.D. Main Hall', 			     location: 'Police Station'},
		'R112': {name: 'R.P.D. Office',					 location: 'Police Station'},
		'R113': {name: 'Files Room',					 location: 'Police Station'},
		'R114': {name: 'Corridor with ladder', 		     location: 'Police Station'},
		'R115': {name: 'Corridor', 					     location: 'Police Station'},
		'R116': {name: 'Press conference Room',			 location: 'Police Station'},
		'R117': {name: 'Dark Room',						 location: 'Police Station'},
		'R118': {name: '2F Corridor', 				     location: 'Police Station'},
		'R119': {name: 'Corridor to S.T.A.R.S. Room',	 location: 'Police Station'},
		'R11A': {name: 'S.T.A.R.S. Room', 			     location: 'Police Station'},
		'R11B': {name: 'Pharmacy', 					     location: 'Uptown'},
		'R11C': {name: 'Pharmacy Product Stock',		 location: 'Uptown'},
		'R11D': {name: 'Alley 1 (Night)', 			     location: 'Uptown'},
		'R11E': {name: 'Street 1 (Night)', 			     location: 'Uptown'},
		'R11F': {name: 'Alley 2 (Night)', 			     location: 'Uptown'},
		'R120': {name: 'Alley 3 (Night)', 			     location: 'Uptown'},
		'R121': {name: 'Boutique Street (Night)', 	     location: 'Uptown'},
		'R122': {name: 'Alley 5 (Night)', 			     location: 'Uptown'},
		'R123': {name: 'Passage to Pharmacy (Night)',	 location: 'Uptown'},
		'R124': {name: 'Main Street (Night)', 		     location: 'Uptown'},
		'R125': {name: 'R.P.D. Gates (Night)', 		     location: 'Police Station'},
		'R200': {name: 'Street 2', 					     location: 'Uptown'},
		'R201': {name: 'Mechanic Parking Lot', 		     location: 'Downtown'},
		'R202': {name: 'Street to Alley 1',	 		     location: 'Downtown'},
		'R203': {name: 'Alley 1', 					     location: 'Downtown'},
		'R204': {name: 'Energy Station Street',			 location: 'Downtown'},
		'R205': {name: 'Grill 13 Street', 			     location: 'Downtown'},
		'R206': {name: 'Shopping Dist.',				 location: 'Downtown'},
		'R207': {name: 'Raccon City Hall Street', 	     location: 'Downtown'},
		'R208': {name: 'Raccon City Hall', 			     location: 'Downtown'},
		'R209': {name: 'Shopping Dist. 2', 			     location: 'Downtown'},
		'R20A': {name: 'Shopping Dist. 3', 			     location: 'Downtown'},
		'R20B': {name: 'Trolley Street',				 location: 'Downtown'},
		'R20C': {name: 'Trolley', 					     location: 'Downtown'},
		'R20D': {name: 'Stagla Gas Station', 			 location: 'Downtown'},
		'R20E': {name: 'Stagla Street', 				 location: 'Downtown'},
		'R20F': {name: 'Press (2F)', 					 location: 'Downtown'},
		'R210': {name: 'Press (1F)', 					 location: 'Downtown'},
		'R211': {name: 'Grill 13 (1F)', 				 location: 'Downtown'},
		'R212': {name: 'Grill 13 (B1)', 				 location: 'Downtown'},
		'R213': {name: 'Energy Station Entrance', 	     location: 'Downtown'},
		'R214': {name: 'Energy Station',				 location: 'Downtown'},
		'R215': {name: 'Trolley (Running)',				 location: 'Downtown'},
		'R216': {name: 'Shopping Dist. Save Room', 	     location: 'Downtown'},
		'R217': {name: 'Stagla Street (After)', 		 location: 'Downtown'},
		'R218': {name: 'Alley to Street 2', 			 location: 'Uptown'},
		'R219': {name: 'Press (1F)', 					 location: 'Downtown'},
		'R21A': {name: 'Alley 6', 					     location: 'Uptown'},
		'R21B': {name: 'Mechanic\'s Office',			 location: 'Downtown'},
		'R300': {name: 'Chapel', 						 location: 'Clock Tower'},
		'R301': {name: 'Piano Hall', 					 location: 'Clock Tower'},
		'R302': {name: 'Dinner Room', 				     location: 'Clock Tower'},
		'R303': {name: 'Clock Tower Garden', 			 location: 'Clock Tower'},
		'R304': {name: 'Main Hall (1F)', 				 location: 'Clock Tower'},
		'R305': {name: 'Resting Room', 				     location: 'Clock Tower'},
		'R306': {name: 'Living Room', 				     location: 'Clock Tower'},
		'R307': {name: 'Clock Tower Library', 		     location: 'Clock Tower'},
		'R308': {name: 'Corridor to Clock Puzzle',	     location: 'Clock Tower'},
		'R309': {name: 'Clock Puzzle', 				     location: 'Clock Tower'},
		'R30A': {name: 'Main Hall (2F)',  			     location: 'Clock Tower'},
		'R30B': {name: 'Tower Balcony',  				 location: 'Clock Tower'},
		'R30C': {name: 'Machinery Room', 				 location: 'Clock Tower'},
		'R30D': {name: 'Clock Tower Garden (Nemesis)',	 location: 'Clock Tower'},
		'R30E': {name: 'Main Hall Destroyed', 		     location: 'Clock Tower'},
		'R30F': {name: 'Piano Hall & Dinner Room', 	     location: 'Clock Tower'},
		'R310': {name: 'Chapel',						 location: 'Clock Tower'},
		'R311': {name: 'Resting Room',		  	 	     location: 'Clock Tower'},
		'R312': {name: 'Living Room', 		  	 	     location: 'Clock Tower'},
		'R313': {name: 'Clock Tower Library (2nd)',		 location: 'Clock Tower'},
		'R314': {name: 'Corridor to Clock Puzzle', 	     location: 'Clock Tower'},
		'R315': {name: 'Clock Puzzle', 				     location: 'Clock Tower'},
		'R316': {name: 'Main Hall Destroyed', 		     location: 'Clock Tower'},
		'R317': {name: 'Piano Hall & Dinner Room', 	     location: 'Clock Tower'},
		'R400': {name: 'Hospital Street', 			     location: 'Park'},
		'R401': {name: 'Park Office', 				     location: 'Park'},
		'R402': {name: 'Hospital Entrance', 			 location: 'Hospital'},
		'R403': {name: 'Hospital Office',   			 location: 'Hospital'},
		'R404': {name: 'Waiting Room', 	  			     location: 'Hospital'},
		'R405': {name: 'Corridor (4F)',     			 location: 'Hospital'},
		'R406': {name: 'Room 402',  					 location: 'Hospital'},
		'R407': {name: 'Room 401',  					 location: 'Hospital'},
		'R408': {name: 'Data Room', 					 location: 'Hospital'},
		'R409': {name: 'Corridor (B3)', 				 location: 'Hospital'},
		'R40A': {name: 'Laboratory 1', 				     location: 'Hospital'},
		'R40B': {name: 'Laboratory 2', 				     location: 'Hospital'},
		'R40C': {name: 'Park Entrance', 				 location: 'Park'},
		'R40D': {name: 'Water Pump Puzzle', 			 location: 'Park'},
		'R40E': {name: 'Bridge', 						 location: 'Park'},
		'R40F': {name: 'Park Exit', 					 location: 'Park'},
		'R410': {name: 'Sewer', 						 location: 'Park'},
		'R411': {name: 'Graveyard',					     location: 'Park'},
		'R412': {name: 'Park Warehouse',				 location: 'Park'},
		'R413': {name: 'Park Warehouse Save Room', 	     location: 'Park'},
		'R414': {name: 'Park Secret Room', 			     location: 'Park'},
		'R415': {name: 'Park Graveyard (Worm)',			 location: 'Park'},
		'R416': {name: '[UNUSED] Copy of R510 (Bridge)', location: 'Park'},
		'R417': {name: 'Park Street', 				     location: 'Park'},
		'R500': {name: 'Factory Entrance', 			     location: 'Dead Factory'},
		'R501': {name: 'Resting Room', 				     location: 'Dead Factory'},
		'R502': {name: 'Steam Room', 					 location: 'Dead Factory'},
		'R503': {name: 'Control Room (1F)', 			 location: 'Dead Factory'},
		'R504': {name: 'Corridor to Monitor Room',	     location: 'Dead Factory'},
		'R505': {name: 'Monitor Room', 				     location: 'Dead Factory'},
		'R506': {name: 'Water Sample Room', 			 location: 'Dead Factory'},
		'R507': {name: 'Control Room (B1)', 			 location: 'Dead Factory'},
		'R508': {name: 'Corridor to Disposal Room', 	 location: 'Dead Factory'},
		'R509': {name: 'Disposal Room', 				 location: 'Dead Factory'},
		'R50A': {name: 'Communication Room', 			 location: 'Dead Factory'},
		'R50B': {name: 'Corridor to Incinerator Room 1', location: 'Dead Factory'},
		'R50C': {name: 'Corridor to Incinerator Room 2', location: 'Dead Factory'},
		'R50D': {name: 'Incinerator Room', 			     location: 'Dead Factory'},
		'R50E': {name: 'Extraction Point', 			     location: 'Dead Factory'},
		'R50F': {name: 'Elevator to Extraction Point',   location: 'Dead Factory'},
		'R510': {name: 'Bridge to Dead Factory', 		 location: 'Park'},
		'R600': {name: '(Merc) Warehouse Save Room',	 location: 'Uptown'},
		'R601': {name: '(Merc) Warehouse',		 	     location: 'Uptown'},
		'R607': {name: '(Merc) Bar Jack',			 	 location: 'Uptown'},
		'R60B': {name: '(Merc) Pharmacy Street', 		 location: 'Uptown'},
		'R60E': {name: '(Merc) Alley 6', 				 location: 'Uptown'},
		'R60F': {name: '(Merc) Unknown Location', 	   	 location: 'Unknown'},
		'R61B': {name: '(Merc) Pharmacy', 	 		     location: 'Uptown'},
		'R61C': {name: '(Merc) Pharmacy Product Stock',  location: 'Uptown'},
		'R61D': {name: '(Merc) Alley 1', 				 location: 'Uptown'},
		'R61E': {name: '(Merc) Street 1',				 location: 'Uptown'},
		'R61F': {name: '(Merc) Alley 2', 				 location: 'Uptown'},
		'R620': {name: '(Merc) Alley 3',				 location: 'Uptown'},
		'R621': {name: '(Merc) Boutique Street',		 location: 'Uptown'},
		'R622': {name: '(Merc) Alley 5',				 location: 'Uptown'},
		'R623': {name: '(Merc) Passage to Pharmacy', 	 location: 'Uptown'},
		'R624': {name: '(Merc) Main Street',		 	 location: 'Uptown'},
		'R700': {name: '(Merc) Street 2 ', 	   		   	 location: 'Downtown'},
		'R701': {name: '(Merc) Mechanic Parking Lot',	 location: 'Downtown'},
		'R702': {name: '(Merc) Street to Alley 1', 	     location: 'Downtown'},
		'R703': {name: '(Merc) Alley 1',				 location: 'Downtown'},
		'R704': {name: '(Merc) Energy Station Street',   location: 'Downtown'},
		'R705': {name: '(Merc) Grill 13 Street',		 location: 'Downtown'},
		'R706': {name: '(Merc) Shopping Dist.',		   	 location: 'Downtown'},
		'R707': {name: '(Merc) Raccon City Hall Street', location: 'Downtown'},
		'R708': {name: '(Merc) Raccon City Hall', 	   	 location: 'Downtown'},
		'R709': {name: '(Merc) Shopping Dist. 2', 	   	 location: 'Downtown'},
		'R70A': {name: '(Merc) Shopping Dist. 3', 	   	 location: 'Downtown'},
		'R70B': {name: '(Merc) Trolley Street',		   	 location: 'Downtown'},
		'R70C': {name: '(Merc) Trolley',				 location: 'Downtown'},
		'R70D': {name: '(Merc) Stagla Gas Station',	   	 location: 'Downtown'},
		'R70E': {name: '(Merc) Stagla Street',		   	 location: 'Downtown'},
		'R70F': {name: '(Merc) Press (2F)',			   	 location: 'Downtown'},
		'R710': {name: '(Merc) Press (1F)',			   	 location: 'Downtown'},
		'R711': {name: '(Merc) Grill 13',				 location: 'Downtown'},
		'R712': {name: '(Merc) Grill 13 (B1)',		     location: 'Downtown'},
		'R713': {name: '(Merc) Energy Station Entrance', location: 'Downtown'},
		'R714': {name: '(Merc) Energy Station',		     location: 'Downtown'},
		'R718': {name: '(Merc) Alley to Street 2', 	     location: 'Uptown'},
		'R71A': {name: '(Merc) Alley 6',				 location: 'Uptown'},
		'R71B': {name: '(Merc) Mechanic\'s Office', 	 location: 'Downtown'}
	}
}